# Generated by Django 2.2.4 on 2019-09-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('second_name', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=300)),
                ('short_cv', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('homework', models.CharField(max_length=1000)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('duration', models.IntegerField()),
                ('lessons', models.ManyToManyField(to='courses.Lesson')),
                ('teachers', models.ManyToManyField(to='courses.Teacher')),
            ],
        ),
    ]
